scaler:
    heroku_app_name: YOUR_APP_NAME
    heroku_api_key: GET_THIS_FROM_ACCOUNT_SCREEN
    min_web_dynos: 2
    max_web_dynos: 20
    dry_run: true    # Will not actually connect to Heroku in this mode
    interval: 5      # Wake up every 5s to check APIs
    blackout: 300    # Do not downscale for this many seconds after scaling up or down.
plugins:
    -
        name: random        # Freeform name
        type: RandomPlugin  # name of the plugin class to use
        interval: 30        # Generate new random number every N seconds
        seed : 12345        # Plugin-specific config
    -
        name: newrelic
        type: NewRelicPlugin
        key: ''
        appid: ''
        users_per_dyno: 100


